### ISSUE TITLE
Please remove usages of branch property from manifests

### ISSUE THREAD

**Issue by bbhtt** [flathub/io.github.arunsivaramanneo.GPUViewer#104]
https://github.com/flathub/io.github.arunsivaramanneo.GPUViewer/blob/5eb161e7e1423d87d3d71a4d313d3e1d8cc598bb/io.github.arunsivaramanneo.GPUViewer.yml#L187

should be tag or commit or tag+commit

**Comment by arunsivaramanneo** [comment]
I believe this is done now .. please let me know otherwise

**Comment by bbhtt** [comment]
Yes thanks.
